pipeline {
    agent any
    stages {
        stage('Git Checkout') {
            steps {
                echo 'Pulling ... '
                git branch: 'main',
                url: 'https://github.com/amen123456/PFE.git'
            }
        }
        stage('Test') {
            steps {
                echo 'amen'
            }
        }

     
      
   stage('Install Wazuh') {
     steps {
                ansiblePlaybook(
                    credentialsId: 'ssh-key', 
                    disableHostKeyChecking: true,
                    installation: 'Ansible',
                    inventory: '/home/amen/PFE/Kubernetes/inventory.txt',
                    playbook: '/home/amen/PFE/Wazuh/Install_wazuh.yml',
                    extraVars: [ 
                        'ansible_user': 'root'
                    ]
                )
            }
}
}
}
