pipeline {
    agent any
    stages {
        stage('Git Checkout') {
            steps {
                echo 'Pulling ... '
                git branch: 'main',
                    url: 'https://github.com/amen123456/PFE.git'
            }
        }
        stage('Test') {
            steps {
                echo 'amen'
            }
        }
        stage('Configure VM Network Settings and Reboot') {
            steps {
                ansiblePlaybook(
                    credentialsId: 'ssh-key',
                    disableHostKeyChecking: true,
                    installation: 'Ansible',
                    inventory: '/home/amen/PFE/Ansible Config IP/hosts.txt',
                    playbook: '/home/amen/PFE/Ansible Config IP/config.yml',
                    extraVars: [
                        'ansible_user': 'root'
                    ]
                )
            }
        }
    }
    post {
        success {
            echo 'Network deployment successful!'
        }
        failure {
            echo 'Network deployment failed.'
        }
    }
}
